In [2]:
import torch

In [3]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x.shape

torch.Size([12])

In [5]:
x.numel()

12

In [6]:
x.size()

torch.Size([12])

In [11]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [15]:
torch.zeros(2, 3, 4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [16]:
torch.randn(3, 4)

tensor([[-0.3442,  0.1716,  0.1140, -0.0225],
        [ 0.6419,  0.6164, -0.7541, -0.9504],
        [-1.9179,  0.0187,  0.4865,  0.0154]])

In [23]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [24]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y        # **运算符是求幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [25]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [26]:
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X, Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]))

In [27]:
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [28]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [29]:
X.sum()

tensor(66.)

In [30]:
a = torch.arange(3).reshape(3, 1)
b = torch.arange(2).reshape(1, 2)
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [31]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [33]:
a * b

tensor([[0, 0],
        [0, 1],
        [0, 2]])

In [34]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [35]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [36]:
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [37]:
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [38]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [42]:
id(X), id(Y)

(3047592442288, 3047592462240)

In [43]:
before = id(Y)
Y = Y + X
id(X), id(Y), before

(3047592442288, 3047592464112, 3047592462240)

In [44]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))

id(Z): 3047592462240


In [46]:
Z[:] = X + Y
Z

tensor([[38., 37., 40., 39.],
        [37., 38., 39., 40.],
        [28., 30., 32., 34.]])

In [47]:
print('id(Z):', id(Z))

id(Z): 3047592462240


In [55]:
A = X.numpy()
# B = torch.tensor(A)
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [56]:
id(A), id(B)

(3047564522096, 3047592465264)

In [57]:
A, B

(array([[12., 12., 12., 12.],
        [12., 12.,  5., 12.],
        [ 8.,  9., 10., 11.]], dtype=float32),
 tensor([[12., 12., 12., 12.],
         [12., 12.,  5., 12.],
         [ 8.,  9., 10., 11.]]))

In [58]:
A[1, 2] = 5
B[2, 3] = 6
A, B, X

(array([[12., 12., 12., 12.],
        [12., 12.,  5., 12.],
        [ 8.,  9., 10.,  6.]], dtype=float32),
 tensor([[12., 12., 12., 12.],
         [12., 12.,  5., 12.],
         [ 8.,  9., 10.,  6.]]),
 tensor([[12., 12., 12., 12.],
         [12., 12.,  5., 12.],
         [ 8.,  9., 10.,  6.]]))

In [59]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [60]:
A.item()

ValueError: can only convert an array of size 1 to a Python scalar

## 练习题部分

In [61]:
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X, Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]))

In [62]:
X == Y, X < Y, X > Y

(tensor([[False,  True, False,  True],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[ True, False,  True, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[False, False, False, False],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]))

In [72]:
a = torch.arange(6).reshape(3, 2, 1)
b = torch.arange(6).reshape(1, 2, 3)
a, b

(tensor([[[0],
          [1]],
 
         [[2],
          [3]],
 
         [[4],
          [5]]]),
 tensor([[[0, 1, 2],
          [3, 4, 5]]]))

In [73]:
a + b

tensor([[[ 0,  1,  2],
         [ 4,  5,  6]],

        [[ 2,  3,  4],
         [ 6,  7,  8]],

        [[ 4,  5,  6],
         [ 8,  9, 10]]])