## 5.4.1 不带参数的层

In [1]:
import torch
import torch.nn.functional as F
from torch import nn

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

In [2]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [3]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

In [5]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(-6.5193e-09, grad_fn=<MeanBackward0>)

## 5.4.2 带参数的层

In [6]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [13]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.5070, -0.1835, -0.0667],
        [-0.7053,  0.4077,  0.3293],
        [-0.2035,  0.0482, -0.4820],
        [ 1.1378, -1.0519, -0.5691],
        [-0.7490, -0.0100,  0.3381]], requires_grad=True)

In [8]:
linear(torch.rand(2, 5))

tensor([[0.0973, 2.8295, 0.0000],
        [0.0000, 2.4987, 0.0000]])

In [11]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[13.8928],
        [10.7511]])